### ISSUE TITLE
Error when running it on Expo Web

### ISSUE THREAD

**Issue by chriswayg** [ReactNativeSchool/master-react-navigation-v5-class#8]
I really enjoyed your course and it helped me to build a cross-platform iOS/Android app which uses a lot of the design patterns from the course. As I am considering to run my app on the web as well, I tested the various components for compatibility. 

Most components do work on the web and React Navigation is marked as React Native Web compatible as well. Therefore I was expecting that this navigation pattern would work as well. But I am getting the error below with your finished course project as well as on my app, which I have not been able to solve:

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
> 
> Check the render method of `ExpoRootComponent`.

I do not see any obvious web incompatibilities in the[ finished code](https://github.com/ReactNativeSchool/master-react-navigation-v5-class/tree/finished/App). 

What could be the solution?

```
  Expo CLI 4.5.2 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.17.0 - ~/.nodenv/versions/14.17.0/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.13 - ~/.nodenv/versions/14.17.0/bin/npm
      Watchman: 2021.06.07.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Android Studio: 4.2 AI-202.7660.26.42.7322048
      Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-native-web: ~0.11.7 => 0.11.7
    Expo Workflow: managed
    
----------------
react-dom.development.js:24036 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `ExpoRootComponent`.
    at http://localhost:19006/static/js/bundle.js:32480:34
    at createFiberFromTypeAndProps (http://localhost:19006/static/js/bundle.js:32483:13)
    at createFiberFromElement (http://localhost:19006/static/js/bundle.js:32504:15)
    at reconcileSingleElement (http://localhost:19006/static/js/bundle.js:22974:23)
    at reconcileChildFibers (http://localhost:19006/static/js/bundle.js:23031:35)
    at reconcileChildren (http://localhost:19006/static/js/bundle.js:25135:28)
    at finishClassComponent (http://localhost:19006/static/js/bundle.js:25500:5)
    at updateClassComponent (http://localhost:19006/static/js/bundle.js:25438:24)
    at beginWork$1 (http://localhost:19006/static/js/bundle.js:26949:16)
    at HTMLUnknownElement.callCallback (http://localhost:19006/static/js/bundle.js:8791:14)
    at Object.invokeGuardedCallbackDev (http://localhost:19006/static/js/bundle.js:8841:16)
    at invokeGuardedCallback (http://localhost:19006/static/js/bundle.js:8898:31)
    at beginWork$$1 (http://localhost:19006/static/js/bundle.js:31661:7)
    at performUnitOfWork (http://localhost:19006/static/js/bundle.js:30655:12)
    at workLoopSync (http://localhost:19006/static/js/bundle.js:30629:22)
    at renderRoot (http://localhost:19006/static/js/bundle.js:30322:11)
    at scheduleUpdateOnFiber (http://localhost:19006/static/js/bundle.js:29863:22)
    at scheduleRootUpdate (http://localhost:19006/static/js/bundle.js:32763:3)
    at updateContainerAtExpirationTime (http://localhost:19006/static/js/bundle.js:32791:10)
    at updateContainer (http://localhost:19006/static/js/bundle.js:32880:10)
    at http://localhost:19006/static/js/bundle.js:33407:7
    at unbatchedUpdates (http://localhost:19006/static/js/bundle.js:30131:12)
    at legacyRenderSubtreeIntoContainer (http://localhost:19006/static/js/bundle.js:33406:5)
    at render (http://localhost:19006/static/js/bundle.js:33486:12)
    at renderApplication (http://localhost:19006/static/js/bundle.js:34214:3)
    at Object.run (http://localhost:19006/static/js/bundle.js:34107:82)
    at Function.runApplication (http://localhost:19006/static/js/bundle.js:34146:23)
    at registerRootComponent (http://localhost:19006/static/js/bundle.js:3588:85)
    at Module.../../../../../../../developer/ReactNativeProjects/master-react-navigation-v5-class-finished/node_modules/expo/AppEntry.js (http://localhost:19006/static/js/bundle.js:3319:88)
    at __webpack_require__ (http://localhost:19006/static/js/bundle.js:790:30)
    at fn (http://localhost:19006/static/js/bundle.js:101:20)
    at Object.1 (http://localhost:19006/static/js/bundle.js:49088:18)
    at __webpack_require__ (http://localhost:19006/static/js/bundle.js:790:30)
    at http://localhost:19006/static/js/bundle.js:857:37
    at http://localhost:19006/static/js/bundle.js:860:10

```

**Comment by spencercarli** [comment]
I _think_ you just need to create an `App.js` file at the root of the project to get it to work. Honestly, I don't really have any experience with Expo Web so I'm still figuring it out.

```js
// App.js

import React from "react";
import App from "./App/index";

export default () => <App />;
```

I'm working to update the project to support the web right now.

**Comment by spencercarli** [comment]
`master` and `finished` now both work on the web. Thanks for bringing this up!
